apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zxctr67ul-nodejs
  janus-idp.io/tekton: zxctr67ul-nodejs
  backstage.io/kubernetes-id: zxctr67ul-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zxctr67ul-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
